### ISSUE TITLE
Need help migrating

### ISSUE THREAD

**Issue by WhoMI7** [zhongfly/command_cond#1]
This is way too hard for me to understand.

I had `inputevent_key.conf` as this:
```
RIGHT           script-binding evafast/speedup                             #@press
RIGHT           script-binding evafast/slowdown                            #@release

SPACE           script-binding simplehistory/history-resume                #@click|idle_active
SPACE           no-osd set speed 3; set pause no                           #@press
SPACE           ignore                                                     #@release

i               script-binding stats/display-stats-toggle  #@click
i               script-binding stats/display-stats         #@repeat
i               script-binding stats/display-stats         #@press

.               frame-step;show-text 'Frame: ${estimated-frame-number}'    #@click
.               set pause no;show-progress;show-text 'Frame: ${estimated-frame-number}'  #@press
.               set pause yes;show-text 'Frame: ${estimated-frame-number}' #@release
.               show-text show-text 'Frame: ${estimated-frame-number}'     #@repeat

k               apply-profile boss-key #@click|not window_minimized
k               apply-profile boss-key restore #@click|window_minimized

MBTN_MID        apply-profile boss-key #@click|not window_minimized
```

Now I don't know what new config to make and biggest question is _where_ to make, since the most recent version of `inputevent.lua` (original) doesn't read `~~/inputevent_key.conf`.
And I still don't understand how do I use `comman_cond.lua` on the same binds as `inputevent.lua`.
```
resume   script-binding simplehistory/history-resume #|idle_active
Space  script-message-to command_cond resume
```
This didn't work, do I need to separate them entirely?
I don't want to use `input.conf`, but rather `inputevent_key.conf` only since more than that would just be a hassle.

Also a request to provide a basic config file that includes `inputevent` binds and `commnd_cond` binds as an example.
For non-engineers like me this might be a lot helpful.

**Comment by zhongfly** [comment]
You should first understand how to use inputevent.
https://github.com/natural-harmonia-gropius/input-event#support-for-multiple-configuration-files
https://github.com/natural-harmonia-gropius/input-event#inputevent

# 1

```
SPACE           script-binding simplehistory/history-resume                #@click|idle_active
```
`#@click` is for `inputevent`,`|idle_active` is for `command_cond`.
So split it to:
1. in `inputevent` configuration file(please read https://github.com/natural-harmonia-gropius/input-event#how-to-use and https://github.com/natural-harmonia-gropius/input-event#support-for-multiple-configuration-files):
    ```
    SPACE script-message-to command_cond A_EXAMPLE_NAME #@click
    ```
2. in `command_cond` configuration file (read https://github.com/zhongfly/command_cond#options):
    ```
    A_EXAMPLE_NAME script-binding simplehistory/history-resume #|idle_active
    ```

# 2
```
k               apply-profile boss-key #@click|not window_minimized
k               apply-profile boss-key restore #@click|window_minimized
```
`#@click` is for `inputevent`,`|not window_minimized` and `|window_minimized` are conditions for `command_cond`.
1. in `inputevent` configuration file(please read https://github.com/natural-harmonia-gropius/input-event#how-to-use and https://github.com/natural-harmonia-gropius/input-event#support-for-multiple-configuration-files):
    ```
    k script-message-to command_cond A_EXAMPLE_NAME #@click
    ```
2. in `command_cond` configuration file (read https://github.com/zhongfly/command_cond#options):
    ```
    A_EXAMPLE_NAME apply-profile boss-key #|not window_minimized
    A_EXAMPLE_NAME apply-profile boss-key restore #|window_minimized
    ```

when click 'k',`inputevent` run command `script-message-to command_cond A_EXAMPLE_NAME`, it means send message to `command_cond` and message's content is 'A_EXAMPLE_NAME'.
So `command_cond` know it should run command related to `A_EXAMPLE_NAME`.`command_cond` look up to its configuration file,find 2 commands and then it determines which one to run based on the conditions.
